-- 1. Table Products (Sembako)
-- Dropping old valid table if exists to ensure clean state or assume user handles migration.
-- We use 'create table if not exists' but warnings about schema mismatch needed if table exists.
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  sku text unique,
  category text,
  stock integer default 0,
  price integer default 0,
  unit text
);

-- 2. Table Transactions (Sales History)
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_id bigint references products (id),
  quantity_sold integer not null,
  sales_person text,
  transaction_date date
);

-- Indexes
create index if not exists transactions_product_id_idx on transactions (product_id);
create index if not exists transactions_date_idx on transactions (transaction_date);
