-- Create stock_movements table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    qty_change INTEGER NOT NULL,
    reason TEXT,
    movement_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Policy to allow anonymous/service role access (standard for this dev setup)
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON public.stock_movements FOR ALL USING (true);
